version: '3.3'

networks:
  netrepopattern:

services:   
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mrjb_repopattern_mssql
    ports:
      - 1443:1443
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '555gpah4jzetczpf'
      MSSQL_PID: 'Developer'
    networks:
      - netrepopattern
  postgresql:
    image: postgres
    container_name: mrjb_repopattern_postgresql
    restart: always
    environment:
      POSTGRES_USER: 'dbuser'
      POSTGRES_PASSWORD: '555gpah4jzetczpf'
    networks:
      - netrepopattern
  mongodb:
    image: mongo
    container_name: mrjb_repopattern_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '555gpah4jzetczpf'
    networks:
      - netrepopattern      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: '555gpah4jzetczpf'
    networks:
      - netrepopattern